// <auto-generated />
using System;
using Conductor.Infrastructure.Persistence.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Conductor.Infrastructure.Persistence.Sqlite.Migrations
{
    [DbContext(typeof(ConductorDbContext))]
    [Migration("20260429025820_PersistNormalizedInstanceSnapshots")]
    partial class PersistNormalizedInstanceSnapshots
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Conductor.Infrastructure.Persistence.Sqlite.Schema.AlertRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SymphonyInstanceId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackedIssueId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("SymphonyInstanceId");

                    b.HasIndex("TrackedIssueId");

                    b.HasIndex("Status", "Severity", "CreatedAtUtc");

                    b.ToTable("Alerts", (string)null);
                });

            modelBuilder.Entity("Conductor.Infrastructure.Persistence.Sqlite.Schema.AuditEventRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId", "OccurredAtUtc");

                    b.ToTable("AuditEvents", (string)null);
                });

            modelBuilder.Entity("Conductor.Infrastructure.Persistence.Sqlite.Schema.BackgroundOperationRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedByUserId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SymphonyInstanceId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("SymphonyInstanceId");

                    b.HasIndex("Status", "CreatedAtUtc");

                    b.ToTable("BackgroundOperations", (string)null);
                });

            modelBuilder.Entity("Conductor.Infrastructure.Persistence.Sqlite.Schema.EventRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SymphonyInstanceId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "OccurredAtUtc");

                    b.HasIndex("SymphonyInstanceId", "OccurredAtUtc");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("Conductor.Infrastructure.Persistence.Sqlite.Schema.InstanceSnapshotRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("ActiveIssueCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicationName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplicationVersion")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedRunCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HealthJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("HealthStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LatencyMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PersistenceProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryQueueCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RunningSessionCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuntimeDefaultsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RuntimeInstanceId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("RuntimeJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("StateJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("SymphonyInstanceId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<long>("TokenInputTotal")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TokenOutputTotal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkflowOwner")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowRepository")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowSourcePath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SymphonyInstanceId", "CapturedAtUtc");

                    b.ToTable("InstanceSnapshots", (string)null);
                });

            modelBuilder.Entity("Conductor.Infrastructure.Persistence.Sqlite.Schema.ProjectRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("Conductor.Infrastructure.Persistence.Sqlite.Schema.ReportRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHtml")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentMarkdown")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("GeneratedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedByUserId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("ReportType", "GeneratedAtUtc");

                    b.ToTable("Reports", (string)null);
                });

            modelBuilder.Entity("Conductor.Infrastructure.Persistence.Sqlite.Schema.RepositoryRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("CloneUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("OpenIssueCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("PullRequestCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("WebUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Provider", "Owner", "Name")
                        .IsUnique();

                    b.ToTable("Repositories", (string)null);
                });

            modelBuilder.Entity("Conductor.Infrastructure.Persistence.Sqlite.Schema.RunAttemptRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogPath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("RunAttempts", (string)null);
                });

            modelBuilder.Entity("Conductor.Infrastructure.Persistence.Sqlite.Schema.RunRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("BranchName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("GitHubIssueNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PullRequestUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SymphonyInstanceId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackedIssueId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TrackedIssueId");

                    b.HasIndex("RepositoryId", "GitHubIssueNumber");

                    b.HasIndex("SymphonyInstanceId", "Status", "StartedAtUtc");

                    b.ToTable("Runs", (string)null);
                });

            modelBuilder.Entity("Conductor.Infrastructure.Persistence.Sqlite.Schema.SecretDescriptorRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RotatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScopeType", "ScopeId", "SecretType");

                    b.ToTable("SecretDescriptors", (string)null);
                });

            modelBuilder.Entity("Conductor.Infrastructure.Persistence.Sqlite.Schema.SymphonyInstanceRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionMode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("GitHubSecretId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("HealthStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastHealthCheckAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenAiSecretId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseSelector")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedReleaseTag")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowProfileId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionMode");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("WorkflowProfileId");

                    b.HasIndex("Status", "HealthStatus");

                    b.ToTable("SymphonyInstances", (string)null);
                });

            modelBuilder.Entity("Conductor.Infrastructure.Persistence.Sqlite.Schema.SymphonyReleaseArtifactRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Checksum")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DownloadedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseTag")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetRuntime")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseTag", "AssetName")
                        .IsUnique();

                    b.ToTable("SymphonyReleaseArtifacts", (string)null);
                });

            modelBuilder.Entity("Conductor.Infrastructure.Persistence.Sqlite.Schema.TrackedIssueRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("AssigneesJson")
                        .HasColumnType("TEXT");

                    b.Property<long>("GitHubIssueNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LabelsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("PullRequestsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("SymphonyStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "GitHubIssueNumber");

                    b.HasIndex("RepositoryId", "SymphonyStatus", "IsBlocked");

                    b.ToTable("TrackedIssues", (string)null);
                });

            modelBuilder.Entity("Conductor.Infrastructure.Persistence.Sqlite.Schema.WorkflowProfileRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionMode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WorkflowProfiles", (string)null);
                });

            modelBuilder.Entity("Conductor.Infrastructure.Persistence.Sqlite.Schema.AlertRecord", b =>
                {
                    b.HasOne("Conductor.Infrastructure.Persistence.Sqlite.Schema.RepositoryRecord", null)
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Conductor.Infrastructure.Persistence.Sqlite.Schema.SymphonyInstanceRecord", null)
                        .WithMany()
                        .HasForeignKey("SymphonyInstanceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Conductor.Infrastructure.Persistence.Sqlite.Schema.TrackedIssueRecord", null)
                        .WithMany()
                        .HasForeignKey("TrackedIssueId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Conductor.Infrastructure.Persistence.Sqlite.Schema.BackgroundOperationRecord", b =>
                {
                    b.HasOne("Conductor.Infrastructure.Persistence.Sqlite.Schema.RepositoryRecord", null)
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Conductor.Infrastructure.Persistence.Sqlite.Schema.SymphonyInstanceRecord", null)
                        .WithMany()
                        .HasForeignKey("SymphonyInstanceId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Conductor.Infrastructure.Persistence.Sqlite.Schema.EventRecord", b =>
                {
                    b.HasOne("Conductor.Infrastructure.Persistence.Sqlite.Schema.RepositoryRecord", null)
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Conductor.Infrastructure.Persistence.Sqlite.Schema.SymphonyInstanceRecord", null)
                        .WithMany()
                        .HasForeignKey("SymphonyInstanceId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Conductor.Infrastructure.Persistence.Sqlite.Schema.InstanceSnapshotRecord", b =>
                {
                    b.HasOne("Conductor.Infrastructure.Persistence.Sqlite.Schema.SymphonyInstanceRecord", null)
                        .WithMany()
                        .HasForeignKey("SymphonyInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Conductor.Infrastructure.Persistence.Sqlite.Schema.ReportRecord", b =>
                {
                    b.HasOne("Conductor.Infrastructure.Persistence.Sqlite.Schema.ProjectRecord", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Conductor.Infrastructure.Persistence.Sqlite.Schema.RepositoryRecord", null)
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Conductor.Infrastructure.Persistence.Sqlite.Schema.RepositoryRecord", b =>
                {
                    b.HasOne("Conductor.Infrastructure.Persistence.Sqlite.Schema.ProjectRecord", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Conductor.Infrastructure.Persistence.Sqlite.Schema.RunAttemptRecord", b =>
                {
                    b.HasOne("Conductor.Infrastructure.Persistence.Sqlite.Schema.RunRecord", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Conductor.Infrastructure.Persistence.Sqlite.Schema.RunRecord", b =>
                {
                    b.HasOne("Conductor.Infrastructure.Persistence.Sqlite.Schema.RepositoryRecord", null)
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Conductor.Infrastructure.Persistence.Sqlite.Schema.SymphonyInstanceRecord", null)
                        .WithMany()
                        .HasForeignKey("SymphonyInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Conductor.Infrastructure.Persistence.Sqlite.Schema.TrackedIssueRecord", null)
                        .WithMany()
                        .HasForeignKey("TrackedIssueId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Conductor.Infrastructure.Persistence.Sqlite.Schema.SymphonyInstanceRecord", b =>
                {
                    b.HasOne("Conductor.Infrastructure.Persistence.Sqlite.Schema.RepositoryRecord", null)
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Conductor.Infrastructure.Persistence.Sqlite.Schema.WorkflowProfileRecord", null)
                        .WithMany()
                        .HasForeignKey("WorkflowProfileId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Conductor.Infrastructure.Persistence.Sqlite.Schema.TrackedIssueRecord", b =>
                {
                    b.HasOne("Conductor.Infrastructure.Persistence.Sqlite.Schema.RepositoryRecord", null)
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
