// <auto-generated />
using System;
using Conductor.Infrastructure.Persistence.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Conductor.Infrastructure.Persistence.Sqlite.Migrations
{
    [DbContext(typeof(ConductorDbContext))]
    partial class ConductorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Conductor.Core.Domain.Alerts.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GitHubIssueNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecommendedAction")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RepositoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SymphonyInstanceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("RunId");

                    b.HasIndex("SymphonyInstanceId");

                    b.HasIndex("Status", "Severity", "CreatedAtUtc");

                    b.ToTable("Alerts", (string)null);
                });

            modelBuilder.Entity("Conductor.Core.Domain.Auditing.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetResourceId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetResourceType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId", "OccurredAtUtc");

                    b.ToTable("AuditEvents", (string)null);
                });

            modelBuilder.Entity("Conductor.Core.Domain.Events.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int?>("IssueNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RepositoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SymphonyInstanceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "OccurredAtUtc");

                    b.HasIndex("SymphonyInstanceId", "OccurredAtUtc");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("Conductor.Core.Domain.Issues.TrackedIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssigneeLoginsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("BlockerReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("GitHubIssueNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LabelsJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastActivityAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastRunStatus")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Milestone")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("SymphonyStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "GitHubIssueNumber");

                    b.HasIndex("RepositoryId", "SymphonyStatus", "IsBlocked");

                    b.ToTable("TrackedIssues", (string)null);
                });

            modelBuilder.Entity("Conductor.Core.Domain.Operations.BackgroundOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorDetail")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetResourceId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetResourceType")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedAtUtc");

                    b.ToTable("BackgroundOperations", (string)null);
                });

            modelBuilder.Entity("Conductor.Core.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultBranchPolicy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("Conductor.Core.Domain.Reports.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("GeneratedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Html")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Markdown")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("PdfPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("PeriodEndUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("PeriodStartUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReportType", "GeneratedAtUtc");

                    b.ToTable("Reports", (string)null);
                });

            modelBuilder.Entity("Conductor.Core.Domain.Repositories.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CloneUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrchestrationStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrchestrationStatusReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("WebUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Provider", "Owner", "Name")
                        .IsUnique();

                    b.ToTable("Repositories", (string)null);
                });

            modelBuilder.Entity("Conductor.Core.Domain.Runs.Run", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BranchName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorSummary")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FinishedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("GitHubIssueNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PullRequestUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SymphonyInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SymphonyRunId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("TokenInput")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TokenOutput")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "GitHubIssueNumber");

                    b.HasIndex("SymphonyInstanceId", "Status", "StartedAtUtc");

                    b.ToTable("Runs", (string)null);
                });

            modelBuilder.Entity("Conductor.Core.Domain.Runs.RunAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorDetail")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExitReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FinishedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("RunAttempts", (string)null);
                });

            modelBuilder.Entity("Conductor.Core.Domain.Secrets.SecretDescriptor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RotatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScopeType", "ScopeId", "SecretType");

                    b.ToTable("SecretDescriptors", (string)null);
                });

            modelBuilder.Entity("Conductor.Core.Domain.Snapshots.InstanceSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("ActiveIssueCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedRunCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HealthJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("HealthStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryQueueCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RunningSessionCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuntimeJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("StateJson")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SymphonyInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<long>("TokenInputTotal")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TokenOutputTotal")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SymphonyInstanceId", "CapturedAtUtc");

                    b.ToTable("InstanceSnapshots", (string)null);
                });

            modelBuilder.Entity("Conductor.Core.Domain.Symphony.SymphonyInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AzureResourceId")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("GitHubCredentialInheritanceMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GitHubCredentialSecretId")
                        .HasColumnType("TEXT");

                    b.Property<string>("HealthStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastHealthCheckAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastStartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LifecycleStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("Status");

                    b.Property<string>("OpenAiCredentialInheritanceMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OpenAiCredentialSecretId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SymphonyArtifactChecksum")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SymphonyArtifactSourceUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("SymphonyReleaseTag")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SymphonyVersion")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionMode");

                    b.HasIndex("GitHubCredentialSecretId");

                    b.HasIndex("OpenAiCredentialSecretId");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("LifecycleStatus", "HealthStatus");

                    b.ToTable("SymphonyInstances", (string)null);
                });

            modelBuilder.Entity("Conductor.Core.Domain.SymphonyReleases.SymphonyReleaseArtifact", b =>
                {
                    b.Property<string>("ReleaseTag")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Checksum")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DownloadedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("ReleaseTag", "AssetName");

                    b.HasIndex("ReleaseTag");

                    b.ToTable("SymphonyReleaseArtifacts", (string)null);
                });

            modelBuilder.Entity("Conductor.Core.Domain.Workflows.WorkflowProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WorkflowProfiles", (string)null);
                });

            modelBuilder.Entity("Conductor.Core.Domain.Alerts.Alert", b =>
                {
                    b.HasOne("Conductor.Core.Domain.Repositories.Repository", null)
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Conductor.Core.Domain.Runs.Run", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Conductor.Core.Domain.Symphony.SymphonyInstance", null)
                        .WithMany()
                        .HasForeignKey("SymphonyInstanceId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Conductor.Core.Domain.Events.Event", b =>
                {
                    b.HasOne("Conductor.Core.Domain.Repositories.Repository", null)
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Conductor.Core.Domain.Symphony.SymphonyInstance", null)
                        .WithMany()
                        .HasForeignKey("SymphonyInstanceId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Conductor.Core.Domain.Issues.TrackedIssue", b =>
                {
                    b.HasOne("Conductor.Core.Domain.Repositories.Repository", null)
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Conductor.Core.Domain.Repositories.Repository", b =>
                {
                    b.HasOne("Conductor.Core.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Conductor.Core.Domain.Runs.Run", b =>
                {
                    b.HasOne("Conductor.Core.Domain.Repositories.Repository", null)
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Conductor.Core.Domain.Symphony.SymphonyInstance", null)
                        .WithMany()
                        .HasForeignKey("SymphonyInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Conductor.Core.Domain.Runs.RunAttempt", b =>
                {
                    b.HasOne("Conductor.Core.Domain.Runs.Run", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Conductor.Core.Domain.Snapshots.InstanceSnapshot", b =>
                {
                    b.HasOne("Conductor.Core.Domain.Symphony.SymphonyInstance", null)
                        .WithMany()
                        .HasForeignKey("SymphonyInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Conductor.Core.Domain.Symphony.SymphonyInstance", b =>
                {
                    b.HasOne("Conductor.Core.Domain.Secrets.SecretDescriptor", null)
                        .WithMany()
                        .HasForeignKey("GitHubCredentialSecretId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Conductor.Core.Domain.Secrets.SecretDescriptor", null)
                        .WithMany()
                        .HasForeignKey("OpenAiCredentialSecretId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Conductor.Core.Domain.Repositories.Repository", null)
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
